---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: stage
networking:
  disableDefaultCNI: true
  podSubnet: 172.16.0.0/16
  kubeProxyMode: "iptables"
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
      extraArgs:
        enable-admission-plugins: AlwaysPullImages
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: data/
    containerPath: /data
    readOnly: false
    selinuxRelabel: false
    propagation: Bidirectional
- role: worker
  extraMounts:
  - hostPath: data/
    containerPath: /data
    readOnly: false
    selinuxRelabel: false
    propagation: Bidirectional
- role: worker
  extraMounts:
  - hostPath: data/
    containerPath: /data
    readOnly: false
    selinuxRelabel: false
    propagation: Bidirectional
